version: "3"

services:
  db:
    build:
      context: ./db
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: domfi_coingecko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_only
